export const BFS_CODE: string[] = [
  'function bfs(graph, start) { // @init',
  '  let queue = [start];',
  '  let visited = new Set();',
  '  while (queue.length > 0) {',
  '    let node = queue.shift(); // @dequeue',
  '    if (visited.has(node)) continue;',
  '    visit(node); // @visit',
  '    visited.add(node); // @mark-visited',
  '    for (let nb of graph[node]) { // @check-neighbor',
  '      if (!visited.has(nb)) {',
  '        queue.push(nb); // @enqueue',
  '      }',
  '    }',
  '  }',
  '} // @done',
];

export const DFS_CODE: string[] = [
  'function dfs(graph, start) { // @init',
  '  let stack = [start];',
  '  let visited = new Set();',
  '  while (stack.length > 0) {',
  '    let node = stack.pop(); // @pop',
  '    if (visited.has(node)) continue;',
  '    visit(node); // @visit',
  '    visited.add(node); // @mark-visited',
  '    for (let nb of graph[node]) { // @check-neighbor',
  '      if (!visited.has(nb)) {',
  '        stack.push(nb); // @push',
  '      }',
  '    }',
  '  }',
  '} // @done',
];
